### ISSUE TITLE
 new PBIAPIClient(ApplicationID) does not work

### ISSUE THREAD

**Issue by agnaldocarmo** [gbrueckl/PowerBI.API.Client#10] opened 2019-01-23 14:00 UTC
AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID:

**Comment by gbrueckl** [comment] 2019-01-23 16:29
So this actually means that you are using a functionality that your are not allowed to use according to permissions of your Azure application (identified by the ClientID/ApplicationID)
for example, if the the application does not have the permission "View all Datasets" and you try to list the Datasets in the API Client, you will get that error. 
Thats by design and how Azure AD applications and their security works

To fix this, you need to extend the permissions of your Azure AD application

can you try this?

**Comment by agnaldocarmo** [comment] 2019-01-23 17:24
in fact I tried to use in an application of the type Desktop WPF

**Comment by gbrueckl** [comment] 2019-01-23 17:44
ok, so I will close this issue then

**Closed by gbrueckl** 2019-01-23 17:44 UTC
